### ISSUE TITLE
Issue on Evaluation values reported

### ISSUE THREAD

**Issue by Sangminhong** [BunnySoCrazy/SECAD-Net#3]
Dear authors, thank you for your interesting work!

While going through your paper, I have found that the evaluation values (CD, ECD, NC) for related works (USG-Net, CSG-Stump) are different from those reported on CAPRI-Net. 
According to the paper, the experiment setting is same as that in CAPRI-Net so do you know why there is some difference in the values? And could you tell me how you computed the values?

Thank you

**Comment by BunnySoCrazy** [comment]
Hi Sangminhong,

Our evaluation code primarily draws upon [BSP-Net](https://github.com/czq142857/BSP-NET-original/tree/master/evaluation). This link contains the code for all the metrics referenced in the paper. I will publish our code along with further details soon. Your interest and patience are much appreciated.

Best regards,
Pu

**Comment by BunnySoCrazy** [comment]
Hello Sangminhong,

The inconsistent results are mainly due to the different subsets of the ABC data set we selected.
I've just uploaded the evaluation code and ABC test list [here](https://github.com/BunnySoCrazy/SECAD-Net/tree/main/eval). If you have any questions, please let me know.

Best regards,
Pu
